language: java
jdk:
  - openjdk11
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw
services:
  - mysql
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n"
  - mysql -u root
  - mysql -e 'DROP DATABASE IF EXISTS contact'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS contact;'